import { Opportunity } from '@/types/opportunity';
import { FreelancerProfile } from '@/types/profile';
import { AgentNodeMetadata, AgentLogEntry } from '@/types/agent';
import { RAGChunk, MatchScoreBreakdown, StepLogItem, WorkflowNode } from '@/types/dashboard';

export const DEMO_PROFILES: FreelancerProfile[] = [
  {
    id: 'prof-ai-cloud-lead',
    name: 'Saved Freelancer',
    title: 'Generative AI & Cloud Data Engineer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Specialized in production Agentic AI workflows, LangGraph pipelines, RAG retrieval architectures, and modern cloud data platforms (Databricks, Snowflake, Azure, Python, SQL).',
    targetRole: 'GenAI & Cloud Data Specialist',
    hourlyRateMin: 60,
    hourlyRateMax: 95,
    currency: 'USD',
    availabilityHoursPerWeek: 25,
    experienceYears: 4,
    preferredPlatforms: ['upwork', 'weworkremotely', 'reddit'],
    locationPreference: 'Remote',
    projectDuration: '2 - 4 weeks',
    skills: [
      { name: 'Generative AI', category: 'ai_ml', yearsExperience: 3, level: 'expert' },
      { name: 'LangGraph / Agentic AI', category: 'ai_ml', yearsExperience: 2, level: 'expert' },
      { name: 'RAG / Vector DBs', category: 'ai_ml', yearsExperience: 3, level: 'expert' },
      { name: 'Python', category: 'backend', yearsExperience: 4, level: 'expert' },
      { name: 'Databricks', category: 'other', yearsExperience: 3, level: 'advanced' },
      { name: 'Snowflake / SQL', category: 'backend', yearsExperience: 3, level: 'advanced' },
      { name: 'Azure', category: 'devops', yearsExperience: 3, level: 'advanced' },
    ],
    portfolioItems: [
      {
        id: 'port-1',
        title: 'Enterprise Multi-Agent RAG Assistant',
        description: 'Architected an Agentic RAG system using LangGraph, pgvector, and Python over 100,000+ technical documents.',
        technologies: ['Generative AI', 'LangGraph', 'RAG', 'Python'],
        liveUrl: 'https://github.com/example/agentic-rag',
        metricsOrOutcome: 'Achieved 96% answer accuracy and cut retrieval latency by 45%.',
      },
      {
        id: 'port-2',
        title: 'Cloud Lakehouse ETL Pipeline',
        description: 'Built scalable ETL pipeline connecting Databricks, Snowflake, and Azure Data Lake for automated ingestion.',
        technologies: ['Databricks', 'Snowflake', 'Azure', 'SQL'],
        metricsOrOutcome: 'Processed 50M+ daily rows with real-time query optimization.',
      },
    ],
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
  },
];

export const MOCK_RAG_CHUNKS: RAGChunk[] = [
  {
    id: 'chunk-1',
    title: 'Work Experience: Senior GenAI & Cloud Engineer',
    description: 'Designed and deployed autonomous multi-agent systems and RAG pipelines using LangGraph, Python, Databricks, Snowflake, and Azure.',
    similarityScore: 0.96,
    isUsedEvidence: true,
    usedReason: 'Direct match with Generative AI, RAG, and Cloud platform requirements.',
    technologies: ['Generative AI', 'LangGraph', 'RAG', 'Python', 'Databricks', 'Azure'],
  },
  {
    id: 'chunk-2',
    title: 'Technical Skills & Cloud Competencies',
    description: 'Expertise in Python, SQL, Databricks, Snowflake, Azure, OpenAI API, vector embeddings (pgvector), and modern cloud pipelines.',
    similarityScore: 0.91,
    isUsedEvidence: false,
    technologies: ['Python', 'Snowflake', 'Databricks', 'Azure', 'SQL'],
  },
];

export const MOCK_MATCH_BREAKDOWN: MatchScoreBreakdown = {
  overallPercentage: 94,
  totalScore: 94,
  maxTotalScore: 100,
  categories: [
    { category: 'Skills Match', score: 40, maxScore: 40, color: 'bg-blue-500' },
    { category: 'Portfolio Evidence', score: 20, maxScore: 20, color: 'bg-cyan-400' },
    { category: 'Budget Fit', score: 15, maxScore: 15, color: 'bg-emerald-400' },
    { category: 'Project Type', score: 9, maxScore: 10, color: 'bg-amber-400' },
    { category: 'Availability Fit', score: 6, maxScore: 10, color: 'bg-purple-400' },
    { category: 'Location Fit', score: 4, maxScore: 5, color: 'bg-violet-400' },
  ],
};

export const MOCK_STEP_LOGS: StepLogItem[] = [
  {
    id: 'step-1',
    agentName: 'Profile Agent',
    action: 'Extracting user requirements & skills',
    timestamp: '16:42:01',
    status: 'completed',
  },
  {
    id: 'step-2',
    agentName: 'Search Agent',
    action: 'Searching across platforms...',
    timestamp: '16:42:02',
    status: 'completed',
  },
  {
    id: 'step-3',
    agentName: 'Search Agent',
    action: '32 opportunities retrieved',
    timestamp: '16:42:04',
    status: 'completed',
  },
  {
    id: 'step-4',
    agentName: 'RAG Agent',
    action: 'Retrieving portfolio evidence...',
    timestamp: '16:42:05',
    status: 'completed',
  },
  {
    id: 'step-5',
    agentName: 'Match Agent',
    action: 'Calculating compatibility scores...',
    timestamp: '16:42:06',
    status: 'completed',
  },
  {
    id: 'step-6',
    agentName: 'Risk Agent',
    action: 'Analyzing risk & scam indicators...',
    timestamp: '16:42:07',
    status: 'completed',
  },
  {
    id: 'step-7',
    agentName: 'Ranking Agent',
    action: 'Ranking top opportunities...',
    timestamp: '16:42:08',
    status: 'completed',
  },
  {
    id: 'step-8',
    agentName: 'Pitch Agent',
    action: 'Generating personalized pitch...',
    timestamp: '16:42:09',
    status: 'completed',
  },
  {
    id: 'step-9',
    agentName: 'Mission Completed',
    action: '7 opportunities found • Top 5 recommended',
    timestamp: '16:42:09',
    status: 'completed',
    isSummary: true,
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-featured',
    title: 'Generative AI & Agentic RAG Pipeline Engineer',
    clientName: 'Nexus Cloud Intelligence',
    clientCountry: 'United States / Remote',
    clientRating: 4.98,
    clientSpent: '$85k+ total spend',
    platform: 'upwork',
    platformUrl: 'https://upwork.com/jobs/genai-rag-pipeline-engineer',
    description: 'We are seeking an experienced Generative AI Engineer to build an enterprise Agentic RAG retrieval pipeline. You will design LangGraph multi-agent workflows, connect with Databricks / Snowflake / Azure cloud backends, and utilize Python & vector embeddings for high-accuracy document intelligence.',
    budgetType: 'hourly',
    budgetMin: 65,
    budgetMax: 95,
    budgetCurrency: 'USD',
    skillsRequired: ['Generative AI', 'LangGraph', 'RAG', 'Python', 'Databricks', 'Snowflake', 'Azure'],
    experienceLevel: 'Intermediate',
    postedAt: '2026-08-10T16:20:00Z',
    estimatedDuration: '2 - 4 weeks',
    status: 'active',
    riskAssessment: {
      score: 6,
      level: 'VERIFIED_SAFE',
      summary: 'Verified enterprise client with 4.98 rating, $85k+ verified payments, and clear technical scope.',
      redFlags: [],
      safetySignals: [
        'Clear hourly compensation ($65 - $95/hr)',
        'Client has verified hiring history on platform',
        'Detailed engineering requirements with modern stack',
        'No suspicious keywords detected',
      ],
      safeToApply: true,
      analyzedAt: '2026-08-10T16:22:00Z',
    },
    matchReasoning: {
      overallScore: 94,
      skillsMatchScore: 95,
      rateAlignmentScore: 94,
      experienceMatchScore: 92,
      whyGoodMatch: [
        'Direct match: Your GenAI, Agentic AI, and RAG competencies align with project scope.',
        'Target budget ($65 - $95/hr) meets and exceeds your minimum rate requirement.',
        'Project duration and remote setup match your availability perfectly.',
      ],
      potentialGaps: [],
      recommendedPitchAngle: 'Highlight your hands-on experience building multi-agent RAG architectures with LangGraph, Python, and cloud data platforms.',
      relevantPortfolioIds: [],
    },
  },
  {
    id: 'opp-1',
    title: 'Build Multi-Agent AI Workflow Dashboard for B2B Logistics',
    clientName: 'LogiVanguard Systems Inc.',
    clientCountry: 'United States',
    clientRating: 4.95,
    clientSpent: '$140k+ total spend',
    platform: 'upwork',
    platformUrl: 'https://upwork.com/jobs/build-multi-agent-ai-logistics',
    description: 'We are seeking an experienced Full-Stack AI Engineer to architect and build a multi-agent orchestration dashboard. You will connect OpenAI models with LangGraph or similar agent framework, integrate Supabase pgvector for internal dispatch memory, and build an interactive Next.js 14 frontend with real-time SSE streaming. Strong TypeScript and modern Tailwind experience required.',
    budgetType: 'hourly',
    budgetMin: 55,
    budgetMax: 80,
    budgetCurrency: 'USD',
    skillsRequired: ['Next.js', 'TypeScript', 'LangGraph', 'Supabase', 'OpenAI', 'Tailwind CSS'],
    experienceLevel: 'Intermediate',
    postedAt: '2026-08-10T14:30:00Z',
    estimatedDuration: '4 to 6 weeks',
    status: 'active',
    riskAssessment: {
      score: 8,
      level: 'VERIFIED_SAFE',
      summary: 'Verified client with 4.95 rating, $140k+ verified platform payments, escrow-backed hourly milestone, and clear technical roadmap.',
      redFlags: [],
      safetySignals: [
        'Client payment method verified with $140,000+ past contract payments.',
        'Clear, realistic scope matching industry rates ($55 - $80/hr).',
        'Official Upwork escrow protection enabled.',
        'Technical requirements are specific and mention modern established libraries.',
      ],
      safeToApply: true,
      analyzedAt: '2026-08-10T14:35:00Z',
    },
    matchReasoning: {
      overallScore: 96,
      skillsMatchScore: 98,
      rateAlignmentScore: 95,
      experienceMatchScore: 94,
      whyGoodMatch: [
        'Direct 100% overlap with your core stack: Next.js, LangGraph, Supabase, and TypeScript.',
        'Client hourly range ($55-$80/hr) perfectly encapsulates your target rate ($50-$85/hr).',
        'Your featured project "Agentic Financial Analyst Bot" demonstrates identical multi-agent streaming architecture.',
      ],
      potentialGaps: [
        'Logistics domain specifics may require a quick kickoff discovery call on their dispatch API.',
      ],
      recommendedPitchAngle: 'Highlight your LangGraph streaming architecture from your Financial Bot and your sub-120ms Supabase vector index experience.',
      relevantPortfolioIds: ['port-ai-1', 'port-ai-2'],
    },
  },
  {
    id: 'opp-2',
    title: 'Enterprise RAG Search Engine with Supabase & Next.js',
    clientName: 'OmniData Health Tech',
    clientCountry: 'Canada',
    clientRating: 4.88,
    clientSpent: '$65k+ spend',
    platform: 'weworkremotely',
    platformUrl: 'https://weworkremotely.com/jobs/enterprise-rag-search',
    description: 'Looking for a developer to implement an enterprise RAG knowledge engine. Needs to parse PDFs, chunk and store embeddings in Supabase pgvector, and expose an intuitive search UI built with Next.js App Router and Tailwind CSS. Clean code and automated evaluations are a plus.',
    budgetType: 'fixed',
    budgetMin: 3500,
    budgetMax: 5000,
    budgetCurrency: 'USD',
    skillsRequired: ['Supabase', 'pgvector', 'Next.js', 'TypeScript', 'OpenAI Embeddings', 'RAG'],
    experienceLevel: 'Intermediate',
    postedAt: '2026-08-10T11:15:00Z',
    estimatedDuration: '3 weeks',
    status: 'active',
    riskAssessment: {
      score: 12,
      level: 'VERIFIED_SAFE',
      summary: 'Reputable healthcare tech company with verified corporate domain, transparent milestone funding, and realistic scope.',
      redFlags: [],
      safetySignals: [
        'Established Canadian corporate entity with verified LinkedIn and web domain.',
        'Fair fixed budget ($3,500 - $5,000) for a 3-week defined deliverables scope.',
        'No off-platform communication demands.',
      ],
      safeToApply: true,
      analyzedAt: '2026-08-10T11:20:00Z',
    },
    matchReasoning: {
      overallScore: 92,
      skillsMatchScore: 95,
      rateAlignmentScore: 90,
      experienceMatchScore: 92,
      whyGoodMatch: [
        'Your "DocuMind" portfolio project is a near identical match for this Supabase pgvector RAG requirement.',
        'Deliverable is well suited for fixed-price execution.',
      ],
      potentialGaps: [
        'Healthcare compliance (HIPAA / PIPEDA awareness) may be asked during interview.',
      ],
      recommendedPitchAngle: 'Present DocuMind benchmark results (sub-120ms retrieval across 50k pages) directly in the proposal hook.',
      relevantPortfolioIds: ['port-ai-2'],
    },
  },
  {
    id: 'opp-3',
    title: 'URGENT: Re-type 50 scanned PDF books into MS Word — $6,000 Weekly ($75/hr)',
    clientName: 'Global Publishing International LLC',
    clientCountry: 'Unknown / Hidden',
    clientRating: 0,
    clientSpent: '$0.00 spent',
    platform: 'freelancer',
    platformUrl: 'https://freelancer.com/projects/retype-scanned-pdf-urgent-6000',
    description: 'URGENT HIRING: We have 50 scanned PDF books that need to be manually re-typed into MS Word documents. Very easy work for students and beginners. We pay $6,000 upon completion. DO NOT APPLY ON FREELANCER PLATFORM — Contact our hiring manager directly on Telegram @Hiring_HR_Global or WhatsApp +1-202-555-0199 with your ID card and bank info to receive the equipment check.',
    budgetType: 'fixed',
    budgetMin: 6000,
    budgetMax: 6000,
    budgetCurrency: 'USD',
    skillsRequired: ['Data Entry', 'Copy Typing', 'MS Word'],
    experienceLevel: 'Entry',
    postedAt: '2026-08-10T15:00:00Z',
    status: 'active',
    riskAssessment: {
      score: 98,
      level: 'CRITICAL_SCAM',
      summary: 'CRITICAL THREAT: Classic fake check / Telegram fee advance scam. Avoid immediately.',
      redFlags: [
        {
          id: 'rf-1',
          category: 'communication',
          severity: 'critical',
          title: 'Off-Platform Redirection (Telegram/WhatsApp)',
          description: 'Client explicitly commands freelancers to bypass platform messaging and contact a Telegram handle.',
          evidence: 'Contact our hiring manager directly on Telegram @Hiring_HR_Global',
        },
        {
          id: 'rf-2',
          category: 'payment',
          severity: 'critical',
          title: 'Unrealistic Pay for Low-Skill Task',
          description: '$6,000 for simple PDF re-typing is 20x-50x above market rates, a hallmark lure of phishing syndicates.',
          evidence: '$6,000 upon completion for re-typing 50 scanned PDF books',
        },
      ],
      safetySignals: [],
      safeToApply: false,
      analyzedAt: '2026-08-10T15:02:00Z',
    },
    matchReasoning: {
      overallScore: 12,
      skillsMatchScore: 10,
      rateAlignmentScore: 5,
      experienceMatchScore: 20,
      whyGoodMatch: [],
      potentialGaps: [
        'This listing is a confirmed fraudulent scam targeting students and freelancers.',
      ],
      recommendedPitchAngle: 'DO NOT APPLY. Risk Sentinel flagged this post.',
      relevantPortfolioIds: [],
    },
  },
];

export const INITIAL_AGENT_NODES: AgentNodeMetadata[] = [
  {
    id: 'supervisor',
    name: 'Profile Agent',
    role: 'Extracts skills, budget, location, availability',
    icon: 'Brain',
    description: 'Decomposes freelancer prompt and extracts structured parameters.',
    status: 'completed',
    executionTimeMs: 140,
    tokensUsed: 420,
    activeMessage: 'Profile parameters extracted.',
  },
  {
    id: 'discovery_agent',
    name: 'Search Agent',
    role: 'Searches gig platforms, job boards, communities',
    icon: 'Radar',
    description: 'Crawls live feeds (Upwork, WWR, Reddit, Freelancer) and parses raw unstructured gig listings.',
    status: 'completed',
    executionTimeMs: 890,
    tokensUsed: 1250,
    itemsProcessed: 32,
    activeMessage: '32 opportunities retrieved.',
  },
  {
    id: 'rag_agent',
    name: 'RAG Agent',
    role: 'Retrieves portfolio evidence from vector DB',
    icon: 'FileCode2',
    description: 'Queries vector database for top matching portfolio items and computes cosine similarity.',
    status: 'completed',
    executionTimeMs: 310,
    tokensUsed: 680,
    itemsProcessed: 3,
    activeMessage: 'Retrieved 3 chunks (Top: 0.94).',
  },
  {
    id: 'risk_agent',
    name: 'Risk Agent',
    role: 'Detects scam & low-ball opportunities',
    icon: 'ShieldAlert',
    description: 'Evaluates 15+ scam signals: Telegram redirection, fake check fraud, unpaid spec work.',
    status: 'completed',
    executionTimeMs: 640,
    tokensUsed: 1890,
    itemsProcessed: 32,
    activeMessage: 'Flagged 1 critical scam.',
  },
  {
    id: 'ranking_agent',
    name: 'Ranking Agent',
    role: 'Ranks gigs based on match + risk + user priority',
    icon: 'Sparkles',
    description: 'Synthesizes skill overlap, budget alignment, schedule match, and generates explainable metrics.',
    status: 'completed',
    executionTimeMs: 420,
    tokensUsed: 980,
    itemsProcessed: 7,
    activeMessage: 'Top 5 recommended.',
  },
  {
    id: 'pitch_agent',
    name: 'Pitch Agent',
    role: 'Generates personalized outreach pitch',
    icon: 'PenTool',
    description: 'Drafts tailored proposals embedding proven portfolio chunks.',
    status: 'completed',
    executionTimeMs: 510,
    tokensUsed: 890,
    itemsProcessed: 1,
    activeMessage: 'Generated pitch preview.',
  },
];

export const SAMPLE_TELEMETRY_LOGS: AgentLogEntry[] = [
  {
    id: 'log-1',
    timestamp: '16:42:01',
    agentId: 'supervisor',
    level: 'info',
    message: 'Profile Agent: Extracting user requirements & skills from prompt',
  },
  {
    id: 'log-2',
    timestamp: '16:42:02',
    agentId: 'discovery_agent',
    level: 'agent_action',
    message: 'Search Agent: Searching across gig platforms, job boards, communities...',
  },
  {
    id: 'log-3',
    timestamp: '16:42:04',
    agentId: 'discovery_agent',
    level: 'success',
    message: 'Search Agent: 32 opportunities retrieved across Upwork, Reddit, WWR.',
  },
  {
    id: 'log-4',
    timestamp: '16:42:05',
    agentId: 'rag_agent',
    level: 'info',
    message: 'RAG Agent: Retrieved top portfolio chunks from vector DB (Top similarity: 0.94).',
  },
  {
    id: 'log-5',
    timestamp: '16:42:06',
    agentId: 'ranking_agent',
    level: 'info',
    message: 'Match Agent: Calculated compatibility scores (Overall Match: 94%).',
  },
  {
    id: 'log-6',
    timestamp: '16:42:07',
    agentId: 'risk_agent',
    level: 'warn',
    message: 'Risk Agent: Screened 32 listings. Clean payment terms verified on top match.',
  },
  {
    id: 'log-7',
    timestamp: '16:42:08',
    agentId: 'ranking_agent',
    level: 'success',
    message: 'Ranking Agent: Ranked top 7 opportunities (Top 5 recommended).',
  },
  {
    id: 'log-8',
    timestamp: '16:42:09',
    agentId: 'pitch_agent',
    level: 'success',
    message: 'Pitch Agent: Generated personalized outreach proposal using candidate portfolio evidence.',
  },
];

export function getInitialOpportunitiesForProfile(profile: FreelancerProfile): Opportunity[] {
  const role = (profile.targetRole || profile.title || '').toLowerCase();
  const skillNames = (profile.skills || []).map(s => (typeof s === 'string' ? s : s.name).toLowerCase());
  const isDataAnalyst = role.includes('data analyst') || role.includes('business intelligence') || role.includes('bi') || skillNames.includes('power bi') || skillNames.includes('tableau');

  if (isDataAnalyst) {
    return [
      {
        id: `opp-bi-${profile.id}-1`,
        title: 'Enterprise Power BI & SQL Business Intelligence Consultant',
        clientName: 'Apex Capital Analytics',
        clientCountry: 'United States / Remote',
        clientRating: 4.97,
        clientSpent: '$92k+ total spend',
        platform: 'upwork',
        platformUrl: 'https://upwork.com/jobs/power-bi-sql-consultant',
        description: 'Seeking an expert Data Analyst & BI Consultant to design executive KPI dashboards in Power BI and optimize SQL data warehouse queries. You will connect PostgreSQL databases, build automated DAX measures, and present performance insights to leadership.',
        budgetType: 'hourly',
        budgetMin: 50,
        budgetMax: 85,
        budgetCurrency: 'USD',
        skillsRequired: ['Power BI', 'SQL', 'DAX', 'Tableau', 'Excel'],
        experienceLevel: 'Intermediate',
        postedAt: '2026-08-10T16:00:00Z',
        estimatedDuration: '2 - 4 weeks',
        status: 'active',
        riskAssessment: {
          score: 5,
          level: 'VERIFIED_SAFE',
          summary: 'Verified client with 4.97 rating and $92k+ escrow payments.',
          redFlags: [],
          safetySignals: ['Verified payment method', 'Clear hourly scope ($50 - $85/hr)', 'No suspicious terms'],
          safeToApply: true,
          analyzedAt: '2026-08-10T16:05:00Z',
        },
        matchReasoning: {
          overallScore: 95,
          skillsMatchScore: 96,
          rateAlignmentScore: 95,
          experienceMatchScore: 94,
          whyGoodMatch: [
            'Direct match: Your Power BI, SQL, and data analytics competencies align with project scope.',
            'Target rate meets your commercial preference.',
            'Remote timeline matches your availability.',
          ],
          potentialGaps: [],
          recommendedPitchAngle: 'Highlight your expertise designing executive Power BI dashboards, SQL query optimization, and actionable business metrics.',
          relevantPortfolioIds: [],
        },
      },
      {
        id: `opp-bi-${profile.id}-2`,
        title: 'Lead Business Analytics & Tableau Dashboard Specialist',
        clientName: 'Horizon Health Systems',
        clientCountry: 'Canada / Remote',
        clientRating: 4.92,
        clientSpent: '$45k+ total spend',
        platform: 'weworkremotely',
        platformUrl: 'https://weworkremotely.com/jobs/tableau-data-analyst',
        description: 'Looking for a Senior Data Analyst to build interactive Tableau and SQL reporting suites for healthcare operations. Must have strong experience transforming raw relational data into clean visual KPI reports.',
        budgetType: 'fixed',
        budgetMin: 3200,
        budgetMax: 5000,
        budgetCurrency: 'USD',
        skillsRequired: ['Tableau', 'SQL', 'Python', 'Power BI'],
        experienceLevel: 'Intermediate',
        postedAt: '2026-08-10T14:30:00Z',
        estimatedDuration: '1 - 2 weeks',
        status: 'active',
        riskAssessment: {
          score: 8,
          level: 'VERIFIED_SAFE',
          summary: 'Verified employer on WeWorkRemotely with established budget.',
          redFlags: [],
          safetySignals: ['Established corporate entity', 'Transparent deliverables'],
          safeToApply: true,
          analyzedAt: '2026-08-10T14:35:00Z',
        },
        matchReasoning: {
          overallScore: 91,
          skillsMatchScore: 92,
          rateAlignmentScore: 90,
          experienceMatchScore: 91,
          whyGoodMatch: ['Strong alignment on Tableau and SQL data analytics requirements.'],
          potentialGaps: [],
          recommendedPitchAngle: 'Showcase visual Tableau reporting suites and SQL extraction pipelines.',
          relevantPortfolioIds: [],
        },
      },
      {
        id: `opp-bi-${profile.id}-3`,
        title: 'SQL Data Modeling & Automated ETL Reporting Pipeline',
        clientName: 'MetricFlow Digital',
        clientCountry: 'United Kingdom / Remote',
        clientRating: 4.88,
        clientSpent: '$60k+ total spend',
        platform: 'reddit',
        platformUrl: 'https://reddit.com/r/forhire/sql-etl-data-analyst',
        description: 'Hiring a freelance Data Analyst for a 2-week engagement to clean, normalize, and build automated SQL queries and Excel/Power BI summaries for customer retention analytics.',
        budgetType: 'hourly',
        budgetMin: 45,
        budgetMax: 75,
        budgetCurrency: 'USD',
        skillsRequired: ['SQL', 'Python', 'Excel', 'Power BI'],
        experienceLevel: 'Intermediate',
        postedAt: '2026-08-10T12:00:00Z',
        estimatedDuration: '1 - 2 weeks',
        status: 'active',
        riskAssessment: {
          score: 12,
          level: 'LOW_RISK',
          summary: 'Reddit job posting with verified upfront milestone payment structure.',
          redFlags: [],
          safetySignals: ['Agreed to upfront milestone escrow'],
          safeToApply: true,
          analyzedAt: '2026-08-10T12:05:00Z',
        },
        matchReasoning: {
          overallScore: 89,
          skillsMatchScore: 90,
          rateAlignmentScore: 88,
          experienceMatchScore: 89,
          whyGoodMatch: ['Direct fit for SQL normalization, Python scripting, and reporting.'],
          potentialGaps: [],
          recommendedPitchAngle: 'Emphasize fast turnaround on SQL modeling and clear automated summary reports.',
          relevantPortfolioIds: [],
        },
      },
    ];
  }

  return INITIAL_OPPORTUNITIES;
}

